#!/usr/bin/env python3
"""Fixture codesign: --force appends a marker line; --verify and -d -r- read it."""
import os
import sys

a = sys.argv[1:]
if os.environ.get("FAKE_CODESIGN_FAIL"):
    print("errSecInternalComponent", file=sys.stderr)
    sys.exit(1)
if a[0] == "--force":
    ident, path = a[a.index("--identifier") + 1], a[-1]
    with open(path, "ab") as fh:
        fh.write(("\nSIGNED:%s:%s\n" % (ident, a[a.index("--sign") + 1])).encode())
elif a[0] == "--verify":
    sys.exit(0 if b"SIGNED:" in open(a[-1], "rb").read() else 1)
elif a[:2] == ["-d", "-r-"]:
    data = open(a[-1], "rb").read().decode("latin1")
    ident = data.split("SIGNED:")[1].split(":")[0]
    print('designated => identifier "%s" and anchor apple generic' % ident)
